[workspace]

members = [
  "cli",
  "client",
  "package",
  "propolis",
  "server",
  "standalone",
  "utils/bhyveadm",
]

default-members = [
  "cli",
  "client",
  "propolis",
  "server",
  "standalone",
  "utils/bhyveadm",
]

[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"
